// supabase/functions/notion-oauth-callback/index.ts
//
// Deploy with: supabase functions deploy notion-oauth-callback --no-verify-jwt
// Set as the redirect_uri in your Notion integration settings:
//   https://YOUR-PROJECT.functions.supabase.co/notion-oauth-callback
//
// Notion redirects here with ?code=...&state=... after the user approves
// the integration. We exchange the code for an access token + database
// selection is done by the user picking a database in-app afterward (Notion
// OAuth for "internal" data-connector style integrations returns a
// workspace-level token, not a page/database — the app's Settings screen
// still asks the user which database id to sync tasks into).
//
// `state` must be the Supabase user's id, set by the app when it opens the
// auth URL, so we know whose user_settings row to update.

const NOTION_CLIENT_ID = Deno.env.get("NOTION_CLIENT_ID")!;
const NOTION_CLIENT_SECRET = Deno.env.get("NOTION_CLIENT_SECRET")!;
const NOTION_REDIRECT_URI = Deno.env.get("NOTION_REDIRECT_URI")!;

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const stateParam = url.searchParams.get("state");
  if (!code || !stateParam) {
    return new Response("Missing code or state", { status: 400, headers: corsHeaders });
  }

  // State can be a plain userId (legacy) or JSON { userId, returnUrl }.
  // returnUrl is the platform-correct deep link: orgnz:// on mobile,
  // http://localhost:8081 on web — generated by Linking.createURL().
  let userId: string;
  let returnUrl: string;
  try {
    const parsed = JSON.parse(stateParam);
    if (typeof parsed === 'object' && parsed !== null && 'userId' in parsed) {
      userId = parsed.userId;
      returnUrl = parsed.returnUrl ?? `orgnz://settings`;
    } else {
      // Valid JSON but not our object shape — treat whole thing as legacy userId
      userId = stateParam;
      returnUrl = `orgnz://settings`;
    }
  } catch {
    // Not JSON — legacy plain-userId format
    userId = stateParam;
    returnUrl = `orgnz://settings`;
  }

  const basic = btoa(`${NOTION_CLIENT_ID}:${NOTION_CLIENT_SECRET}`);
  const tokenRes = await fetch("https://api.notion.com/v1/oauth/token", {
    method: "POST",
    headers: {
      Authorization: `Basic ${basic}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      grant_type: "authorization_code",
      code,
      redirect_uri: NOTION_REDIRECT_URI,
    }),
  });
  const tokenJson = await tokenRes.json();
  if (!tokenRes.ok) {
    return new Response(`Notion token exchange failed: ${JSON.stringify(tokenJson)}`, { status: 502 });
  }

  const supabaseAdmin = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  await supabaseAdmin
    .from("user_settings")
    .upsert({ user_id: userId, notion_access_token: tokenJson.access_token }, { onConflict: "user_id" });

  // Redirect back to the app using the platform-correct URL from state.
  // Mobile: orgnz://settings?notion=connected
  // Web:     http://localhost:8081/settings?notion=connected
  const finalUrl = `${returnUrl}?notion=connected`;
  return new Response(null, {
    status: 302,
    headers: { ...corsHeaders, Location: finalUrl },
  });
});
